
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://WebService/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param code
     * @return
     *     returns proxy.Compte
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consulter", targetNamespace = "http://WebService/", className = "proxy.Consulter")
    @ResponseWrapper(localName = "consulterResponse", targetNamespace = "http://WebService/", className = "proxy.ConsulterResponse")
    @Action(input = "http://WebService/BanqueService/consulterRequest", output = "http://WebService/BanqueService/consulterResponse")
    public Compte consulter(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Compte>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listComptes", targetNamespace = "http://WebService/", className = "proxy.ListComptes")
    @ResponseWrapper(localName = "listComptesResponse", targetNamespace = "http://WebService/", className = "proxy.ListComptesResponse")
    @Action(input = "http://WebService/BanqueService/listComptesRequest", output = "http://WebService/BanqueService/listComptesResponse")
    public List<Compte> listComptes();

    /**
     * 
     * @param mt
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "convertir", targetNamespace = "http://WebService/", className = "proxy.Convertir")
    @ResponseWrapper(localName = "convertirResponse", targetNamespace = "http://WebService/", className = "proxy.ConvertirResponse")
    @Action(input = "http://WebService/BanqueService/convertirRequest", output = "http://WebService/BanqueService/convertirResponse")
    public double convertir(
        @WebParam(name = "mt", targetNamespace = "")
        double mt);

}
